### ISSUE TITLE
Requesting data and code for reproducing results

### ISSUE THREAD

**Issue by rahulrathnakumar** [djene-mengistu/simEps#1]
Hey!
Interesting work! I was wondering if you had any code samples to reproduce the results of your work. Also, in your paper you say that you have used 6 classes from the DAGM dataset with a total of 1350 samples. However, there are 10 classes in the DAGM dataset with 6 of them used for training and the last 4 used for testing. Can you provide clarity on this?

**Comment by djene-mengistu** [comment]
@rahulrathnakumar Thank you for showing interest in our work. We will soon release the implementation code of our research. For the DAGM dataset, we selected six representative classes among the 10 classes for defect segmentation. We only selected defective samples to train and validate the performance of our method. The selected six classes are presented in the paper.

**Comment by rahulrathnakumar** [comment]
Thank you!
